<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;

class Package extends Model
{
    protected $table = 'packages';
    protected $guarded = [];

    protected $appends = ['image'];


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($model) {
            File::delete(public_path('images/packages/' . $model->photo));
        });
    }

    public function getImageAttribute()
    {
        if (!$this->photo) {
            return asset('default/default.png');
        }
        return asset('images/packages/' . $this->photo);


    }//end of getImageAttribute function

    public function companies()
    {
        return $this->hasMany(Company::class);


    }//end of companies function
}
