<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/bootstrap/css/bootstrap.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/animate/animate.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/animate/custom-animate.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/fontawesome/css/all.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/jarallax/jarallax.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/jquery-magnific-popup/jquery.magnific-popup.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/nouislider/nouislider.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/nouislider/nouislider.pips.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/odometer/odometer.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/swiper/swiper.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/wostin-icons/style.css">
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/tiny-slider/tiny-slider.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/reey-font/stylesheet.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/owl-carousel/owl.carousel.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/owl-carousel/owl.theme.default.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/bxslider/jquery.bxslider.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/bootstrap-select/css/bootstrap-select.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/vegas/vegas.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/jquery-ui/jquery-ui.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/vendors/timepicker/timePicker.css"/>
<link rel="stylesheet" href="{{asset('assets/website')}}/css/style.css"/>
<link rel="stylesheet" href="{{asset('assets/website/plugins/toaster/css/toastr.min.css')}}">
